// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tax/calculations": {
            "post": {
                "description": "Calculates taxes based on total income, withholding tax, and allowances.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "Calculate taxes",
                "parameters": [
                    {
                        "description": "Tax Calculation Request",
                        "name": "tax_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.TaxStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the calculated tax amount",
                        "schema": {
                            "$ref": "#/definitions/structs.TaxResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input parameters",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tax/calculations/upload-csv": {
            "post": {
                "description": "Calculates taxes based on total income, withholding tax, and allowances. CSV",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "Calculate taxes CSV",
                "parameters": [
                    {
                        "description": "Tax Calculation Request",
                        "name": "tax_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.TaxStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the calculated tax amount",
                        "schema": {
                            "$ref": "#/definitions/structs.TaxResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input parameters",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "structs.AllowanceStruct": {
            "type": "object",
            "properties": {
                "allowanceType": {
                    "type": "string",
                    "enum": [
                        "donation",
                        "k-receipt"
                    ]
                },
                "amount": {
                    "type": "number",
                    "minimum": 0
                }
            }
        },
        "structs.TaxLevelData": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "tax": {
                    "type": "number"
                }
            }
        },
        "structs.TaxResponse": {
            "type": "object",
            "properties": {
                "tax": {
                    "type": "number"
                },
                "taxLevel": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structs.TaxLevelData"
                    }
                },
                "taxRefund": {
                    "type": "number"
                }
            }
        },
        "structs.TaxStruct": {
            "type": "object",
            "properties": {
                "allowances": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structs.AllowanceStruct"
                    }
                },
                "totalIncome": {
                    "type": "number",
                    "minimum": 0
                },
                "wht": {
                    "type": "number",
                    "minimum": 0
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
